# Generated by Django 3.2.1 on 2024-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20240628_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='latitude',
            field=models.FloatField(default=31.9686),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='longitude',
            field=models.FloatField(default=99.9018),
        ),
    ]
