# Generated by Django 3.2.1 on 2024-06-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_deliveryorder_ordertracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
